fix: Ruff rule EXE001 (shebang-not-executable)
boriel-basic/zxbasic pull request #899
Opened 2024-11-18 21:43 UTC by bartsanchez

https://docs.astral.sh/ruff/rules/shebang-not-executable/

2024-11-19 20:50 UTC, boriel approved these changes

2024-11-19 20:53 UTC, boriel requested changes
Sorry :-(

After a 2nd review, I realized that It should be exactly the opposite: remove that shebang from all non-executable files.
Only zxbc.py, zxbasm.py and zxbpp.py (in root folder and src/ sub-folders) should be executable. The rest should be imported.

2024-11-20 22:01 UTC, bartsanchez commented
> Sorry :-(
> 
> After a 2nd review, I realized that It should be exactly the opposite: remove that shebang from all non-executable files. Only zxbc.py, zxbasm.py and zxbpp.py (in root folder and src/ sub-folders) should be executable. The rest should be imported.

OK, cool. No worries. I am modifying the PR.

2024-11-20 22:56 UTC, bartsanchez commented
Note that the following files are also defining a shebang but they are executable:

```
❯ rg "env python" --files-with-matches
tools/normalize_asm.py
tools/scrview.py
tools/mulfix.py
tools/nextcreator.py
tools/normalize_bas.py
zxbc.py
tests/runtime/update_test.py
tests/runtime/check_test.py
tests/functional/test_basic.py
tests/functional/test_.py
tests/functional/test_prepro.py
tests/functional/test.py
tests/functional/test_asm.py
zxbpp.py
zxbasm.py
src/zxbpp/zxbpplex.py
src/zxbpp/zxbpp.py
src/zxbasm/zxbasm.py
src/zxbasm/asmparse.py
src/zxbc/zxblex.py
src/zxbasm/asmlex.py
src/arch/z80/__init__.py
src/arch/z80/beep.py
src/zxbc/zxbc.py
src/zxbc/zxbparser.py
src/arch/zx48k/__init__.py
src/arch/zx48k/beep.py
src/arch/zxnext/__init__.py
src/outfmt/tap.py
src/outfmt/tzx.py
```

2024-11-22 08:45 UTC, boriel approved these changes

2024-11-22 08:46 UTC, merged