Adds isdigit() and isletter() to string.bas
boriel-basic/zxbasic pull request #917
Opened 2024-11-29 20:23 UTC by Baltasarq

Adds both functions to library, file string.bas:

- isletter(ByVal a$) -- returns true if the first position of the string is a letter.
- isdigit(ByVal a$)  -- return true if the first position of the string is a digit

The code just returns the result of the conditional expression, so it should be okay about that boolean normalization.

2024-12-06 18:33 UTC, boriel requested changes

2024-12-06 18:33 UTC, boriel commented on tests/functional/arch/zx48k/string_isdigit_isletter.bas
.BAS test files should go in arch/zx48k or arch/zxnext (depending on the architecture) below this folder.
However these tests are to test compiler translations to asm (at a more _atomic_ level).

This is not the case. This test should go in the _runtime_ directory and is a more complex case.
Leave it out and I till tell you how to add it in a later PR. :-)

2024-12-08 12:40 UTC, Baltasarq commented on tests/functional/arch/zx48k/string_isdigit_isletter.bas
Lib string.bas  mirrored on zxnext (I mean, boith new functions). Test removed.

2024-12-08 12:57 UTC, boriel approved these changes

2024-12-08 12:57 UTC, boriel commented on src/lib/arch/zx48k/stdlib/string.bas
Thanks! :-)

2024-12-08 12:58 UTC, merged